### ISSUE TITLE
The metadata wrong links are incorrect

### ISSUE THREAD

**Issue by markodukic** [nhsconnect/careconnect-reference-implementation#13]
In the following link there is the incorrect linking to the profiles as the profiles do not resolve
Metadata link:
http://194.189.27.193/careconnect/STU3/metadata
Link which can not be followed: 
<reference value="http://hl7.org/fhir/Profile/OperationDefinition"/>
& 
<reference value="http://hl7.org/fhir/Profile/Patient"/>
&
<reference value="http://hl7.org/fhir/Profile/StructureDefinition"/>

**Comment by KevinMayfield** [comment]
Believe part of this ticket is missing. What are the ampersand links?

**Comment by markodukic** [comment]
StructureDef and OpDef
