### ISSUE TITLE
Inclusion of StructureDefinition & OperationDefinition

### ISSUE THREAD

**Issue by markodukic** [nhsconnect/careconnect-reference-implementation#14]
Should the StructureDefinition & OperationDefinition be included in the capability statement. They have not been tested

**Comment by KevinMayfield** [comment]
This is core hapi behaviour. Think this should be suppressed from the UI (hapi overlay) at least.

**Comment by ahatherly** [comment]
I don't think it is - I've done FHIR endpoints with HAPI without this issue. The CapabilityStatement is generated based on which ResourceProviders you implement, and which methods you override on them.

**Comment by KevinMayfield** [comment]
We’re only adding one resource provider. I think we need to check if we need to provide structured definition (and operation definition). Fhir website mentions them as conformance resources and I could see reasons why they would be required - couldn’t see if they were a SHALL or a SHOULD though.

**Comment by KevinMayfield** [comment]
I believe we need to produce our own CapabilityStatement, looks to be a small task. (It's something we intended to do when we added security anyway) 
We also need to set the profile we are using @ CapabilityStatement.rest.resource.profile.

**Comment by swk003** [comment]
@ CapabilityStatement.rest.resource.profile  should ref the base care connect profile

**Comment by KevinMayfield** [comment]
Next release
