### ISSUE TITLE
https support?

### ISSUE THREAD

**Issue by freshehr** [nhsconnect/careconnect-reference-implementation#58]
I am trying to access the Patient endpoint via a very simple browser-client demo hosted on heroku. 

This app sits behind https and as such the browser raises 'Mixed content' warnings because the ccri endpoints are http only.

I tried switching to https ccri endpoints but got a certificate expired error.

Is it intended to make ccri available via https?

**Comment by KevinMayfield** [comment]
Yes, it’s a SMART on FHIR endpoint. Did you follow the instructions on the implementation guide. Certificate maybe a red herring.

**Comment by KevinMayfield** [comment]
Thanks Ian for reporting.

Certificates have now been renewed.

**Comment by KevinMayfield** [comment]
closing
