### ISSUE TITLE
UI should implement search on _id using an id

### ISSUE THREAD

**Issue by Dunmail** [nhsconnect/careconnect-reference-implementation#59]
UI implements search by _id as an identifier search using system/value:
http://yellow.testlab.nhs.uk/careconnect-ri/resource?serverId=home&pretty=true&resource=Condition__

_id is one of the common parameters and should be an id field. See: http://hl7.org/fhir/stu3/search.html#all

**Comment by KevinMayfield** [comment]
Can you explain a little more? Is this just a UI issue.

**Comment by KevinMayfield** [comment]
It looks like a UI issue only.

**Comment by KevinMayfield** [comment]
Issue with HAPI UI components. 

_id search parameter uses TokenParam which causes the UI to display both system and value boxes. The system parameter is ignored, need to investigate if we can drop the search box for _id parameters.

**Comment by Dunmail** [comment]
Incidentally, 'Use the following code snippet to execute this action in your own client.' doesn't work for my client :)

**Comment by KevinMayfield** [comment]
Removed code generation and altered the js code to only supply id input box
