### ISSUE TITLE
The search prefix 'ne' is not working on dates.

### ISSUE THREAD

**Issue by markodukic** [nhsconnect/careconnect-reference-implementation#6]
http://194.189.27.193/careconnect/STU3/Patient?birthdate=ne1918-05-20
Add this possibility to the other servers. Provide a list of what is not appropriate and what should be supported in the Imp Guide

**Comment by markodukic** [comment]
Review at end of release 2

**Comment by KevinMayfield** [comment]
Fixed on spring 4/5
