### ISSUE TITLE
Value annotations in HAPIRestfulConfig are not applied

### ISSUE THREAD

**Issue by martinwaite** [nhsconnect/careconnect-reference-implementation#60]
Inside the HAPIRestfulConfig class, there are half-a-dozen attempts to set configuration variables using the @Value annotation, for example:
```
	@Value("${fhir.oauth2.authorize:https://auth.hspconsortium.org/authorize}")
	private String oauth2authorize = "http://purple.testlab.nhs.uk:20080/authorize";
```
At the time these variables are used, in the initialize method, these @Value expressions have not been applied.  I think this is because the HAPIRestfulConfig class is not marked for scanning when Spring resolves property values, and so the @Value expressions are ignored.

I think these configuration variables should be moved into the Config class which has been declared asa @Configuration class and so @Value resolution should work.  Inside the Config class, the relevant variables could be wrapped into one or more @Bean(s) for later retrieval by the HAPIRestfulConfig.initialize method.   

I will try to prepare a fix later this week, and I am interested in any comments or guidance.

**Comment by KevinMayfield** [comment]
Patch applied
