### ISSUE TITLE
ccrigatewayhttps - intermittent problem with "illegal cyclic inheritance" error 

### ISSUE THREAD

**Issue by martinwaite** [nhsconnect/careconnect-reference-implementation#62]
On my host (CentOS7, mvn 3.0.5, java 1.8), some builds yield ccrigatewayhttps war files that are difficult to start.  This is caused by two versions of lib/bcprov-*.jar getting pulled in by the build.  The classes in this jar define a circular dependency between org.bouncycastle.asn1.ASN1EncodableVector and org.bouncycastle.asn1.DEREncodableVector.  If you are lucky, at start up this cycle is resolved in the same jar file and all works fine.  If you are unlucky, the classes are pulled from different versions of the jar and an infinite loop kicks off.   See https://stackoverflow.com/questions/17584495/unable-to-complete-the-scan-for-annotations-for-web-application-app-due-to-a for a similar situation.

The fix that worked for me was to add a packagingExcludes clause into the pom.xml file to eliminate one of the redundant jar files:  I picked the one with the oldest version and now the service starts for me every time.

I will post a patch for the pom.xml file later.

**Comment by KevinMayfield** [comment]
please do. I've been meaning to get around to diagnosing that problem.
