### ISSUE TITLE
Cant Start - Missing careconnect-ri.war?

### ISSUE THREAD

**Issue by dollis-developer** [nhsconnect/careconnect-reference-implementation#66]
Hi, I am getting the below error when trying to start the latest release?

ERROR: Service 'ccri' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder404952759/target/careconnect-ri.war: no such file or directory

**Comment by kevthecoder** [comment]
Could you let me know how you resolved this @dollis-developer, we're seeing the same issue. 

Tried doing a maven build before running `docker-compose up` but doesn't seem to resolve the issue.

**Comment by dollis-developer** [comment]
We never got it working to be honest, I closed the issue as I thought it was something we had done wrong

**Comment by KevinMayfield** [comment]
I'm presuming you are using the docker-compose in the repository? 
We use that in jenkins but a different one on our demo server. I'll have a look.

**Comment by KevinMayfield** [comment]
Can you try setting the docker-compose version to 2.

`version: '2'
services:
  ccri:
    container_name: ccri
    image: thorlogic/ccri-fhirserver:${CRRI_VERSION}
    depends_on:
      - ccrisql
    links:
      - ccrisql
    environment:
      - datasource.username=${MYSQL_DB_USER}
      - datasource.password=${MYSQL_DB_PASSWORD}
      - datasource.host=//ccrisql
      - datasource.driver=org.postgresql.Driver
      - datasource.path=5432/careconnect
      - datasource.vendor=postgresql
      - datasource.showSql=true
      - datasource.showDdl=true
      - datasource.cleardown.cron=0 19 21 * * *
      - datasource.dialect=org.hibernate.dialect.PostgreSQL9Dialect
      - datasource.ui.serverBase=http://${FHIR_SERVER_BASE_HOST}/careconnect-ri/STU3
      - datasource.serverBase=http://${FHIR_SERVER_BASE_HOST}/careconnect-ri/STU3
    ports:
      - 8080:8080
    extra_hosts:
      # Define an alias to loop back for REST Connections
      - "${FHIR_SERVER_BASE_HOST}:127.0.0.1"
    volumes:
      - tomcat-log-volume:/usr/local/tomcat/logs
    networks:
      ccri_net:
        ipv4_address: 172.168.240.10

  ccrisql:
    container_name: ccrisql
    #   image: mysql:5.7.20
    image: thorlogic/ccri-sql:latest
    environment:
      - POSTGRES_DB=careconnect
      - POSTGRES_USER=${MYSQL_DB_USER}
      - POSTGRES_PASSWORD=${MYSQL_DB_PASSWORD}
    ports:
      - 20002:5432
    networks:
      - ccri_net


  ccridl:
    container_name: ccridl
    image: thorlogic/ccri-dataload:latest
    depends_on:
      - ccri
    environment:
      - FHIR_SERVER=http://ccri:8080/careconnect-ri/STU3
      - POSTGRES_JDBC=postgresql://ccrisql:5432/careconnect
      - POSTGRES_DB=careconnect
      - POSTGRES_USERNAME=${MYSQL_DB_USER}
      - POSTGRES_USER=${MYSQL_DB_USER}
      - POSTGRES_PASSWORD=${MYSQL_DB_PASSWORD}
    networks:
      ccri_net:
        ipv4_address: 172.168.240.13

  ccriui:
    container_name: ccriui
    image: thorlogic/ccri-ui:${CRRI_VERSION}
    environment:
      - datasource.ui.serverBase=http://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - fhir.resource.serverBase=https://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
    depends_on:
      - ccrifhir
    ports:
      - 80:80
    extra_hosts:
      - "${FHIR_SERVER_BASE_HOST}:172.168.240.14"
    networks:
      - ccri_net
 
  ccrifhir:
    container_name: ccrifhir
    image: thorlogic/ccri-fhir:${CRRI_VERSION}
    environment:
      - datasource.ui.serverBase=http://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - fhir.resource.serverBase=https://${FHIR_SERVER_BASE_HOST}/ccri-fhir/STU3
      - fhir.restserver.serverBase=http4://ccri:8080/careconnect-ri/STU3?throwExceptionOnFailure=false&bridgeEndpoint=true
      - fhir.restserver.tieBase=http4://ccritie:8182/STU3?throwExceptionOnFailure=false&bridgeEndpoint=true
      - fhir.restserver.edmsBase=http4://ccridocument:8181/STU3?throwExceptionOnFailure=false&bridgeEndpoint=true
    depends_on:
      - ccri
    ports:
      - 89:80
    extra_hosts:
      - "${FHIR_SERVER_BASE_HOST}:127.0.0.1"
    volumes:
      - gateway-log-volume:/usr/local/tomcat/logs
    networks:
      ccri_net:
        ipv4_address: 172.168.240.14

volumes:
  tomcat-log-volume:
  gateway-log-volume:
  gatewayssl-log-volume:
  mongo-log-volume:
  tie-log-volume:
  sqlvol:

networks:
  ccri_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.168.240.0/24`

**Comment by KevinMayfield** [comment]
Note: this is using postgres unlike the previous docker-compose. 

You might want to leave off the ccri-smartonfhir section. The ccridl is a work in progress, it loads in reference data for the server (mostly codes), it should work though.

**Comment by kevthecoder** [comment]
Thanks for the replies, sorry didn't notice them until now. 

The Docker Compose file above let me get the containers running thanks (I just commented out the network sections). I've only looked at the db container so far, but hopefully the other containers are running ok too.

**Comment by KevinMayfield** [comment]
I've added a new docker-compose file https://github.com/nhsconnect/careconnect-reference-implementation/blob/master/docker-compose.public.yml

To pull down the images I'm using this command 

docker-compose -f docker-compose.public.yml pull

To start up the server

docker-compose -f docker-compose.public.yml up

After a while (~5 mins for database to be built) you can then access:

UI on http://127.0.0.1/ccri

(MAIN) EPR FHIR Server http://127.0.0.1:8109/careconnect-ri/STU3/metadata 
 
EDMS FHIR Server http://127.0.0.1:8107/STU3/metadata

TIE FHIR Server: http://127.0.0.1:8105/ccri-fhir/STU3/metadata 

postgress is running on 8106 and mongo 8107

**Comment by dollis-developer** [comment]
Great, will spin this up tomorrow, thanks for your help!

**Comment by dollis-developer** [comment]
This all appeared to be going well until attempting to connect to postgres, I still have the environment variables set from the initial setup, have they changed?

[https://nhsconnect.github.io/CareConnectAPI/build_ri_install.html](url)

CRRI_VERSION=latest
FHIR_SERVER_BASE_HOST=test.myserver.nhs.uk
MYSQL_DB_USER=fhirjpa
MYSQL_DB_PASSWORD=fhirjpa
ELASTIC_SEARCH_USER=elasticsearch
ELASTIC_SEARCH_PASSWORD=changeme


![capture](https://user-images.githubusercontent.com/32422784/44585358-f3683200-a7a3-11e8-8f4d-aff1efdc2e82.PNG)

**Comment by KevinMayfield** [comment]
That should work. Do you have any errors earlier on?

I ran the docker-compose without any environment variables though (but fhirjpa is the default username and password, so it should cause any problems)

**Comment by dollis-developer** [comment]
Heres the full log:

https://pastebin.com/3RDCSQP7

**Comment by KevinMayfield** [comment]
It’s looking like a database connection issue, I think Postgres isn’t picking up the username and password from the enivironment variables.
I’ll see if I can get a colleague to look at it.

**Comment by KevinMayfield** [comment]
Closing as new docker-compose files have been produced and instructions updated.
