### ISSUE TITLE
ccriserver failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder007796907/target/ccri-fhirserver.jar: no such file or directory

### ISSUE THREAD

**Issue by tim-jones-anthropos** [nhsconnect/careconnect-reference-implementation#67]
Fresh repo clone, startServer.sh fails:

```
Step 4/5 : ADD target/ccri-fhirserver.jar ccri-fhirserver.jar
ERROR: Service 'ccriserver' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder007796907/target/ccri-fhirserver.jar: no such file or directory
```
(Have tried on Mac and Fedora with the same result)

Similar sounding issue to  issue #66 (Cant Start - Missing careconnect-ri.war?), but link to alternative docker-compose file suggested by @KevinMayfield broken

Any suggestions?

**Comment by tim-jones-anthropos** [comment]
If you amend the .env and the docker-compose.yml along the lines of the example at [CCRI Installation instructions](https://nhsconnect.github.io/CareConnectAPI/build_ri_install.html) instead of the one in the repo, this problem does not occur

**Comment by KevinMayfield** [comment]
The one in the repo is for our jenkins server. Will look at adding a note in the readme file
