### ISSUE TITLE
The search prefix 'sa' is not working on dates.

### ISSUE THREAD

**Issue by markodukic** [nhsconnect/careconnect-reference-implementation#7]
http://194.189.27.193/careconnect/STU3/Patient?birthdate=sa2015-05-11
Expected 200-OK Bundle with 3 patients (1046. 1053 & 1068) returned.
Received 200-OK 0 Patients,

**Comment by markodukic** [comment]
Review at end of Release 2

**Comment by KevinMayfield** [comment]
Fixed on spring 4/5
